### ISSUE TITLE
Update readme with markdown rich code formatting

### ISSUE THREAD

**Issue by harry-olabs** [harry-olabs/avi-hub#2]
### Description

Make use of GitHub markdown rich formatting to format code blocks. You can read about code formatting in the [GitHub Docs](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code)

### TODO

- [x] Update the highlighted area with inline or code block formatting

<img width="759" alt="Screenshot 2023-06-07 at 14 09 33" src="https://github.com/harry-olabs/avi-hub/assets/135703492/75bb8ec8-b6cd-44ad-81f3-665cdc9439b0">

**Comment by Doyin02** [comment]
I have updated the areas you highlighted
